### ISSUE TITLE
Slot Checker (line 33)

### ISSUE THREAD

**Issue by Ershubhambhagat** [irajankumar/Cowin-Covid-vaccine-slot-finder#1]
I get this Error when running on my Pc. Please check it. 

if(len(Data['Centers']))<=0:

keyError: 'centers'

**Comment by irajankumar** [comment]
Looks like you have Capital 'C' in 'centers' while actual code have small 'c' in centers.  Please check.

**Comment by Ershubhambhagat** [comment]
once copy by git clone and try to run.
